version: "3"
services:
  web:
    container_name: quot_lambda
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DYNAMO_ENDPOINT=http://rakugaki_db:8000
      - AWS_ACCESS_KEY_ID=aaa
      - AWS_SECRET_ACCESS_KEY=aaa
      - AWS_SESSION_TOKEN=aaa
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080
    networks:
      - network

  db:
    container_name: dynamo_a
    image: amazon/dynamodb-local:latest
    user: root
    command: -jar DynamoDBLocal.jar sharedDb -dbPath /var/lib/dynamo/data -optimizeDbBeforeStartup
    volumes:
      - ./tmp/db:/var/lib/dynamo/data
    ports:
      - 8000:8000
    networks:
      - network

networks:
  network:
    driver: bridge
